title:             定风波
email:             dingfengboo@qq.com
description:       竹仗芒鞋轻胜马,一笠烟雨任平生
author:            chenyihui
baseurl:           "/dingfengboo.github.io"
url:               "http://dingfengboo.github.io"

# Social Profiles
#twitter_username:  SBootstrap
github_username:   dingfengboo
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
